deploy_to_cloudflare_pages:
  stage: deploy
  image: node:22
  variables:
    CLOUDFLARE_ACCOUNT_ID: "424d9dabd39849818d9e22366a20e4d6"
    CLOUDFLARE_PROJECT_NAME: "www-zue-dev"
    CLOUDFLARE_API_TOKEN: $CLOUDFLARE_API_TOKEN
  script:
    - echo "Checking out code..."
    - git checkout $CI_COMMIT_REF_NAME
    - echo "Installing dependencies..."
    - npm install
    - echo "Building project..."
    - npm run build
    - echo "Copying Cloudflare files..."
    - cp -r cloudflare/* out/
    - echo "Deploying to Cloudflare Pages..."
    - npx @cloudflare/pages-cli@latest deploy out --token $CLOUDFLARE_API_TOKEN --account-id $CLOUDFLARE_ACCOUNT_ID --project-name $CLOUDFLARE_PROJECT_NAME
