name: Gitlab Sync

on: [push, pull_request, create, delete]

jobs:
  sync:
    name: Gitlab Sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: action-pack/gitlab-sync@v3
        with:
          username: zuedev
          url: https://gitlab.com/zuedev/zue.dev.git
          token: ${{ secrets.GITLAB_TOKEN }}
